# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adc_controler.xdc

# Block Designs: bd/test/test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_processing_system7_0_1/test_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_processing_system7_0_1 || ORIG_REF_NAME==test_processing_system7_0_1} -quiet] -quiet

# IP: bd/test/ip/test_adc_controler_0_0/test_adc_controler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_adc_controler_0_0 || ORIG_REF_NAME==test_adc_controler_0_0} -quiet] -quiet

# IP: bd/test/ip/test_ps7_0_axi_periph_1/test_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_ps7_0_axi_periph_1 || ORIG_REF_NAME==test_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/test/ip/test_rst_ps7_0_50M_1/test_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_rst_ps7_0_50M_1 || ORIG_REF_NAME==test_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/test/ip/test_auto_pc_0/test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_auto_pc_0 || ORIG_REF_NAME==test_auto_pc_0} -quiet] -quiet

# XDC: bd/test/test_ooc.xdc
