# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3.xci
# IP: The module: 'cateen_axi_gpio_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cateen_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cateen_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'cateen_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3.xci
# IP: The module: 'cateen_axi_gpio_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cateen_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cateen_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'cateen_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
