# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# Block Designs: bd/cateen/cateen.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen || ORIG_REF_NAME==cateen} -quiet] -quiet

# IP: bd/cateen/ip/cateen_processing_system7_0_0/cateen_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_processing_system7_0_0 || ORIG_REF_NAME==cateen_processing_system7_0_0} -quiet] -quiet

# IP: bd/cateen/ip/cateen_hx711_zynq_0_0/cateen_hx711_zynq_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_hx711_zynq_0_0 || ORIG_REF_NAME==cateen_hx711_zynq_0_0} -quiet] -quiet

# IP: bd/cateen/ip/cateen_ps7_0_axi_periph_0/cateen_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_ps7_0_axi_periph_0 || ORIG_REF_NAME==cateen_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cateen/ip/cateen_rst_ps7_0_50M_0/cateen_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_rst_ps7_0_50M_0 || ORIG_REF_NAME==cateen_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/cateen/ip/cateen_xbar_0/cateen_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_xbar_0 || ORIG_REF_NAME==cateen_xbar_0} -quiet] -quiet

# IP: bd/cateen/ip/cateen_axi_gpio_0_0/cateen_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_axi_gpio_0_0 || ORIG_REF_NAME==cateen_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cateen/ip/cateen_axi_gpio_1_0/cateen_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_axi_gpio_1_0 || ORIG_REF_NAME==cateen_axi_gpio_1_0} -quiet] -quiet

# IP: bd/cateen/ip/cateen_axi_gpio_1_1/cateen_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_axi_gpio_1_1 || ORIG_REF_NAME==cateen_axi_gpio_1_1} -quiet] -quiet

# IP: bd/cateen/ip/cateen_axi_gpio_1_2/cateen_axi_gpio_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_axi_gpio_1_2 || ORIG_REF_NAME==cateen_axi_gpio_1_2} -quiet] -quiet

# IP: bd/cateen/ip/cateen_axi_gpio_1_3/cateen_axi_gpio_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_axi_gpio_1_3 || ORIG_REF_NAME==cateen_axi_gpio_1_3} -quiet] -quiet

# IP: bd/cateen/ip/cateen_auto_pc_0/cateen_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cateen_auto_pc_0 || ORIG_REF_NAME==cateen_auto_pc_0} -quiet] -quiet

# XDC: bd/cateen/cateen_ooc.xdc
