# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/rfid_zynq.xdc

# Block Designs: bd/rfid/rfid.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid || ORIG_REF_NAME==rfid} -quiet] -quiet

# IP: bd/rfid/ip/rfid_processing_system7_0_0/rfid_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_processing_system7_0_0 || ORIG_REF_NAME==rfid_processing_system7_0_0} -quiet] -quiet

# IP: bd/rfid/ip/rfid_axi_gpio_0_0/rfid_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_axi_gpio_0_0 || ORIG_REF_NAME==rfid_axi_gpio_0_0} -quiet] -quiet

# IP: bd/rfid/ip/rfid_axi_gpio_1_0/rfid_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_axi_gpio_1_0 || ORIG_REF_NAME==rfid_axi_gpio_1_0} -quiet] -quiet

# IP: bd/rfid/ip/rfid_axi_gpio_1_1/rfid_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_axi_gpio_1_1 || ORIG_REF_NAME==rfid_axi_gpio_1_1} -quiet] -quiet

# IP: bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_axi_gpio_1_2 || ORIG_REF_NAME==rfid_axi_gpio_1_2} -quiet] -quiet

# IP: bd/rfid/ip/rfid_axi_gpio_1_3/rfid_axi_gpio_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_axi_gpio_1_3 || ORIG_REF_NAME==rfid_axi_gpio_1_3} -quiet] -quiet

# IP: bd/rfid/ip/rfid_xbar_0/rfid_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_xbar_0 || ORIG_REF_NAME==rfid_xbar_0} -quiet] -quiet

# IP: bd/rfid/ip/rfid_ps7_0_axi_periph_0/rfid_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_ps7_0_axi_periph_0 || ORIG_REF_NAME==rfid_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/rfid/ip/rfid_rst_ps7_0_50M_0/rfid_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_rst_ps7_0_50M_0 || ORIG_REF_NAME==rfid_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/rfid/ip/rfid_auto_pc_0/rfid_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfid_auto_pc_0 || ORIG_REF_NAME==rfid_auto_pc_0} -quiet] -quiet

# XDC: bd/rfid/rfid_ooc.xdc
