# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2.xci
# IP: The module: 'rfid_axi_gpio_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfid_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfid_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfid_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2.xci
# IP: The module: 'rfid_axi_gpio_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfid_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfid_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_axi_gpio_1_2/rfid_axi_gpio_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfid_axi_gpio_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
