# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_processing_system7_0_0/cateen_processing_system7_0_0.xci
# IP: The module: 'cateen_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_processing_system7_0_0/cateen_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cateen_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_processing_system7_0_0/cateen_processing_system7_0_0.xci
# IP: The module: 'cateen_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/cateen/cateen.srcs/sources_1/bd/cateen/ip/cateen_processing_system7_0_0/cateen_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cateen_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
