set_property SRC_FILE_INFO {cfile:E:/project/SmartCanteen/module_test/system_zynq/yubow/zynq/zynq.srcs/constrs_1/new/adc_controler.xdc rfile:../../../zynq.srcs/constrs_1/new/adc_controler.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports dout_0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports pd_sck_0]
