# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_xbar_0/rfid_xbar_0.xci
# IP: The module: 'rfid_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_xbar_0/rfid_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfid_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_xbar_0/rfid_xbar_0.xci
# IP: The module: 'rfid_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/module_test/system_zynq/rfid_zynq.srcs/sources_1/bd/rfid/ip/rfid_xbar_0/rfid_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfid_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
