# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hx711_zynq.xdc

# Block Designs: bd/hx711_zynq/hx711_zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hx711_zynq || ORIG_REF_NAME==hx711_zynq} -quiet] -quiet

# IP: bd/hx711_zynq/ip/hx711_zynq_processing_system7_0_0/hx711_zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hx711_zynq_processing_system7_0_0 || ORIG_REF_NAME==hx711_zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/hx711_zynq/ip/hx711_zynq_hx711_package_0_0/hx711_zynq_hx711_package_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hx711_zynq_hx711_package_0_0 || ORIG_REF_NAME==hx711_zynq_hx711_package_0_0} -quiet] -quiet

# IP: bd/hx711_zynq/ip/hx711_zynq_ps7_0_axi_periph_0/hx711_zynq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hx711_zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==hx711_zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hx711_zynq/ip/hx711_zynq_rst_ps7_0_50M_0/hx711_zynq_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hx711_zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==hx711_zynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/hx711_zynq/ip/hx711_zynq_auto_pc_0/hx711_zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hx711_zynq_auto_pc_0 || ORIG_REF_NAME==hx711_zynq_auto_pc_0} -quiet] -quiet

# XDC: bd/hx711_zynq/hx711_zynq_ooc.xdc
