# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project/SmartCanteen/module_test/system_zynq/hx711_zynq/hx711_zynq.srcs/sources_1/bd/hx711_zynq/ip/hx711_zynq_processing_system7_0_0/hx711_zynq_processing_system7_0_0.xci
# IP: The module: 'hx711_zynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/module_test/system_zynq/hx711_zynq/hx711_zynq.srcs/sources_1/bd/hx711_zynq/ip/hx711_zynq_processing_system7_0_0/hx711_zynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hx711_zynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/project/SmartCanteen/module_test/system_zynq/hx711_zynq/hx711_zynq.srcs/sources_1/bd/hx711_zynq/ip/hx711_zynq_processing_system7_0_0/hx711_zynq_processing_system7_0_0.xci
# IP: The module: 'hx711_zynq_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/SmartCanteen/module_test/system_zynq/hx711_zynq/hx711_zynq.srcs/sources_1/bd/hx711_zynq/ip/hx711_zynq_processing_system7_0_0/hx711_zynq_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hx711_zynq_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
